services:
    oro.form.type.issue:
        class: 'ORO\Bundle\IssueBundle\Form\Type\IssueType'
        arguments: ['%issue.types%']
        tags:
            - { name: form.type, alias: issue }

    issue.form.type.issue_api:
        class: 'ORO\Bundle\IssueBundle\Form\Type\IssueApiType'
        arguments: ['%issue.types%']
        tags:
            - { name: form.type, alias: api_issue }

    issue.form:
        class: Symfony\Component\Form\Form
        factory: ['@form.factory', 'createNamed']
        arguments:
            - issue
            - issue


    issue.form.api:
        class: Symfony\Component\Form\Form
        factory: ['@form.factory', 'createNamed']
        arguments:
            - api_issue
            - api_issue

    form.handler.api_issue:
        class: 'ORO\Bundle\IssueBundle\Form\Handler\IssueApiHandler'
        scope: request
        arguments:
            - '@issue.form'
            - '@request'
            - '@doctrine.orm.entity_manager'


    form.handler.issue:
        class: 'ORO\Bundle\IssueBundle\Form\Handler\IssueHandler'
        scope: request
        arguments:
            - '@issue.form'
            - '@request'
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: oro_tag.tag_manager }
