oro_menu_config:
    items:
        issues:
            label: 'oro.issue.menu.label'
            route: 'issue_index'
        issues_report:
            label: 'oro.issue.report'
            route: 'oro_report_index'
            routeParameters:
                reportGroupName: issues
                reportName:      issues


    tree:
        application_menu:
            children:
                activities_tab:
                    children:
                        issues: ~
                reports_tab:
                    children:
                        issues_report: ~

oro_titles:
    issue_index: ~
    issue_view: '%%code%%'
    issue_create: oro.ui.create_entity
    issue_update: 'Update %%code%%'
