oro_menu_config:
    items:
        issues:
            label: 'oro.issue.menu.label'
            route: 'issue_index'
        issues_report:
            label: 'oro.issue.menu.label'
            route: 'issue_index'
            routeParameters:
                reportGroupName: issues
                reportName:      issues


    tree:
        application_menu:
            children:
                activities_tab:
                    children:
                        issues: ~
                reports_tab:
                    children:
                        issues_report: ~
