oro_menu_config:
    items:
        issues:
            label: 'oro.issue.menu.label'
            route: 'issue_index'

    tree:
        application_menu:
            children:
                activities_tab:
                    children:
                        issues: ~
