parameters:
  issue.entity.class: ORO\Bundle\IssueBundle\Entity\Issue
  issue.types:
        Bug: Bug
        Task: Task
        Story: Story
        Subtask: Subtask


services:
    issue.manager.api:
        class: Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager
        parent: oro_soap.manager.entity_manager.abstract
        arguments:
          - 'ORO\Bundle\IssueBundle\Entity\Issue'
          - '@doctrine.orm.entity_manager'

    issue.note.listener:
        class: ORO\Bundle\IssueBundle\EventListener\NoteListener
        tags:
          - { name: doctrine.event_listener, event: postPersist, method: postPersist }

    issue.entity.listener:
        class: 'ORO\Bundle\IssueBundle\EventListener\IssueListener'
        arguments:
                    - '@oro_navigation.content.topic_sender'
        tags:
            - { name: doctrine.orm.entity_listener }


    # Export
    oro.importexport.template_fixture.issue:
            class: 'ORO\Bundle\IssueBundle\ImportExport\TemplateFixture\IssueFixture'
            tags:
                - { name: oro_importexport.template_fixture }

    oro.importexport.template_fixture.data_converter.issue:
        parent: oro_importexport.data_converter.template_fixture.configurable

    oro.importexport.data_converter.issue:
        parent: oro_importexport.data_converter.configurable

    oro.importexport.processor.export_template.issue:
        parent: oro_importexport.processor.export_abstract
        calls:
            - [setDataConverter, ['@oro.importexport.template_fixture.data_converter.issue']]
        tags:
            - { name: oro_importexport.processor, type: export_template, entity: '%issue.entity.class%', alias: issue_template }

    oro.importexport.processor.export.issue:
            parent: oro_importexport.processor.export_abstract
            calls:
                 - [setDataConverter, ['@oro.importexport.data_converter.issue']]
            tags:
                - { name: oro_importexport.processor, type: export, entity: '%issue.entity.class%', alias: issue_export }

    oro.importexport.strategy.issue.add_or_replace:
        parent: oro_importexport.strategy.configurable_add_or_replace

    oro.importexport.processor.import.issue:
        parent: oro_importexport.processor.import_abstract
        calls:
          - [setDataConverter, ['@oro.importexport.data_converter.issue']]
          - [setStrategy, ['@oro.importexport.strategy.issue.add_or_replace']]
        tags:
          - { name: oro_importexport.processor, type: import, entity: '%issue.entity.class%', alias: issue_import }
          - { name: oro_importexport.processor, type: import_validation, entity: '%issue.entity.class%', alias: issue_import }

